### ISSUE TITLE
Failed to activate the transform package

### ISSUE THREAD

**Issue by timfallmk** [eins78/atom-transform#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 15.04
**Thrown From**: [transform](https://github.com/eins78/atom-transform) package, v0.3.0

### Stack Trace

Failed to activate the transform package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at /home/tfall/.atom/packages/transform/lib/transform.coffee:33:36
    at Object.module.exports.activate (/home/tfall/.atom/packages/transform/lib/transform.coffee:38:11)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
    at /usr/share/atom/resources/app.asar/src/package.js:772:25
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:222:20)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
```

### Commands

```
  4x -0:12.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:09.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:03.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 transform:capitalize (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-dockerfile",
      "atom-speech-to-code"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.5.1
atom-html-preview, v0.1.8
atom-text-transformer, v0.7.0
atomatigit, v1.5.3
feedback, v0.38.0
git-go, v1.0.1
language-asciidoc, v0.11.1
language-docker, v1.1.3
language-puppet, v0.12.0
linkify, v0.11.0
linter-puppet, v1.0.0
minimap, v4.10.0
minimap-git-diff, v4.1.3
the-closer, v0.5.0
transform, v0.3.0

# Dev
No dev packages
```

**Comment by andrelima** [comment]
@eins78 This has been solved, right? If yes, please close this issue...
